# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-10-24 11:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0016_auto_20181019_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statsproduct',
            name='year_create',
            field=models.CharField(max_length=50),
        ),
    ]
